package com.whitescan.app
import com.whitescan.app.ui.FormState
import org.json.JSONObject
internal fun FormState.toJson():String=JSONObject().apply{
put("speedDownloadUrl",speedDownloadUrl)
put("speedDuration",speedDuration)
put("speedMaxMb",speedMaxMb)
put("targetType",targetType)
put("antiDpi",antiDpi)
put("fragmentSize",fragmentSize)
put("fragmentDelay",fragmentDelay)
put("proxyTestUrl",proxyTestUrl)
put("countTotal",countTotal)
put("targets",targets)
put("ports",ports)
put("concurrency",concurrency)
put("lowBandwidth",lowBandwidth)
put("transferModel",transferModel)
put("sniDomains",sniDomains)
put("sniStrict",sniStrict)
put("edgeProvider",edgeProvider)
put("edgeProbeDomains",edgeProbeDomains)
put("fastMode",fastMode)
put("verboseLog",verboseLog)
put("liteMode",liteMode)
put("dnsProtocol",dnsProtocol)
put("dnsReference",dnsReference)
put("dnsScanDepth",dnsScanDepth)
put("dnsTestNearby",dnsTestNearby)
put("dnsRate",dnsRate)
put("dnsRatePerResolver",dnsRatePerResolver)
put("dnsBurst",dnsBurst)
put("dnsJitter",dnsJitter)
put("speedTestEnabled",speedTestEnabled)
put("e2eEnabled",e2eEnabled)
put("e2eDomain",e2eDomain)
put("e2ePubKey",e2ePubKey)
put("e2eTransport",e2eTransport)
}.toString()
internal fun formFromJson(raw:String):FormState{val json=JSONObject(raw);val defaults=FormState();return FormState(
speedDownloadUrl=json.optString("speedDownloadUrl",defaults.speedDownloadUrl),
speedDuration=json.optString("speedDuration",defaults.speedDuration),
speedMaxMb=json.optString("speedMaxMb",defaults.speedMaxMb),
targetType=json.optString("targetType",defaults.targetType),
antiDpi=json.optBoolean("antiDpi",defaults.antiDpi),
fragmentSize=json.optString("fragmentSize",defaults.fragmentSize),
fragmentDelay=json.optString("fragmentDelay",defaults.fragmentDelay),
proxyTestUrl=json.optString("proxyTestUrl",defaults.proxyTestUrl),
countTotal=json.optBoolean("countTotal",defaults.countTotal),
targets=json.optString("targets",defaults.targets),
ports=json.optString("ports",defaults.ports),
concurrency=json.optString("concurrency",defaults.concurrency),
lowBandwidth=json.optBoolean("lowBandwidth",defaults.lowBandwidth),
transferModel=json.optString("transferModel",defaults.transferModel),
sniDomains=json.optString("sniDomains",defaults.sniDomains),
sniStrict=json.optBoolean("sniStrict",defaults.sniStrict),
edgeProvider=json.optString("edgeProvider",defaults.edgeProvider),
edgeProbeDomains=json.optString("edgeProbeDomains",defaults.edgeProbeDomains),
fastMode=json.optBoolean("fastMode",defaults.fastMode),
verboseLog=json.optBoolean("verboseLog",defaults.verboseLog),
liteMode=json.optBoolean("liteMode",defaults.liteMode),
dnsProtocol=json.optString("dnsProtocol",defaults.dnsProtocol),
dnsReference=json.optString("dnsReference",defaults.dnsReference),
dnsScanDepth=json.optString("dnsScanDepth",defaults.dnsScanDepth),
dnsTestNearby=json.optBoolean("dnsTestNearby",defaults.dnsTestNearby),
dnsRate=json.optString("dnsRate",defaults.dnsRate),
dnsRatePerResolver=json.optString("dnsRatePerResolver",defaults.dnsRatePerResolver),
dnsBurst=json.optString("dnsBurst",defaults.dnsBurst),
dnsJitter=json.optString("dnsJitter",defaults.dnsJitter),
speedTestEnabled=json.optBoolean("speedTestEnabled",defaults.speedTestEnabled),
e2eEnabled=json.optBoolean("e2eEnabled",defaults.e2eEnabled),
e2eDomain=json.optString("e2eDomain",defaults.e2eDomain),
e2ePubKey=json.optString("e2ePubKey",defaults.e2ePubKey),
e2eTransport=json.optString("e2eTransport",defaults.e2eTransport),
)}
